// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://poqpzwwniqxwcttlyodu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBvcXB6d3duaXF4d2N0dGx5b2R1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU2ODk5MzgsImV4cCI6MjA3MTI2NTkzOH0.yR9_hu37-YJ6YpJzcDA8q4kgszFUgbAxcWbPyf9LA0U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});